-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity NormalISP_p_anonymous_namespace_awb_gains_q8_Pipeline_VITIS_LOOP_147_1_VITIS_LOOP_149_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    mul_ln147 : IN STD_LOGIC_VECTOR (61 downto 0);
    sext_ln147 : IN STD_LOGIC_VECTOR (62 downto 0);
    width : IN STD_LOGIC_VECTOR (30 downto 0);
    cnt_b_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    cnt_b_out_ap_vld : OUT STD_LOGIC;
    cnt_g_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    cnt_g_out_ap_vld : OUT STD_LOGIC;
    sum_r_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    sum_r_out_ap_vld : OUT STD_LOGIC;
    sum_g_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    sum_g_out_ap_vld : OUT STD_LOGIC;
    sum_b_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    sum_b_out_ap_vld : OUT STD_LOGIC;
    cnt_r_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    cnt_r_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of NormalISP_p_anonymous_namespace_awb_gains_q8_Pipeline_VITIS_LOOP_147_1_VITIS_LOOP_149_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv62_0 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv62_1 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv16_20 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv25_1FFDFC0 : STD_LOGIC_VECTOR (24 downto 0) := "1111111111101111111000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv9_133 : STD_LOGIC_VECTOR (8 downto 0) := "100110011";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_11E : STD_LOGIC_VECTOR (8 downto 0) := "100011110";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln147_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln147_reg_741 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln147_reg_741_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln147_reg_741_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln149_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln149_reg_745 : STD_LOGIC_VECTOR (0 downto 0);
    signal v_reg_750 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln81_1_fu_309_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln81_1_reg_757 : STD_LOGIC_VECTOR (0 downto 0);
    signal v_36_fu_430_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal v_36_reg_764 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_ln81_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln81_reg_769 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln81_reg_769_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln82_fu_443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln82_reg_775 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln82_reg_775_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln82_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln82_reg_781 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln82_reg_781_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln70_s_reg_786 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_69_reg_791 : STD_LOGIC_VECTOR (0 downto 0);
    signal cnt_r_fu_118 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal cnt_r_2_fu_466_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal sum_b_fu_122 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal sum_b_2_fu_597_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum_g_fu_126 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal sum_g_2_fu_604_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum_r_fu_130 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal sum_r_2_fu_611_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal cnt_g_fu_134 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal cnt_g_2_fu_479_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal cnt_b_fu_138 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal cnt_b_2_fu_487_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_fu_142 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln149_fu_313_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal y_fu_146 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal select_ln147_fu_342_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten_fu_150 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000000";
    signal add_ln147_fu_276_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal select_ln145_fu_301_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln147_1_fu_336_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_66_fu_358_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_67_fu_369_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln96_fu_365_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln96_18_fu_376_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln96_18_fu_380_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln96_fu_386_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln95_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_392_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln70_fu_402_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_68_fu_414_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln70_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln70_fu_410_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln81_fu_349_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal cnt_r_1_fu_448_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal cnt_g_1_fu_454_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal cnt_b_1_fu_460_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln82_fu_518_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln81_fu_525_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln98_fu_536_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln98_fu_536_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln98_fu_536_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal v_37_fu_569_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln155_fu_575_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum_b_1_fu_591_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum_g_1_fu_585_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum_r_1_fu_579_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln98_fu_536_p00 : STD_LOGIC_VECTOR (20 downto 0);
    signal mul_ln98_fu_536_p10 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component NormalISP_mul_12ns_9ns_21_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;


    component NormalISP_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_12ns_9ns_21_1_1_U1 : component NormalISP_mul_12ns_9ns_21_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 12,
        din1_WIDTH => 9,
        dout_WIDTH => 21)
    port map (
        din0 => mul_ln98_fu_536_p0,
        din1 => mul_ln98_fu_536_p1,
        dout => mul_ln98_fu_536_p2);

    flow_control_loop_pipe_sequential_init_U : component NormalISP_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    cnt_b_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    cnt_b_fu_138 <= ap_const_lv64_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    cnt_b_fu_138 <= cnt_b_2_fu_487_p3;
                end if;
            end if; 
        end if;
    end process;

    cnt_g_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    cnt_g_fu_134 <= ap_const_lv64_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    cnt_g_fu_134 <= cnt_g_2_fu_479_p3;
                end if;
            end if; 
        end if;
    end process;

    cnt_r_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    cnt_r_fu_118 <= ap_const_lv64_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    cnt_r_fu_118 <= cnt_r_2_fu_466_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_150 <= ap_const_lv62_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln147_fu_271_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_150 <= add_ln147_fu_276_p2;
                end if;
            end if; 
        end if;
    end process;

    sum_b_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    sum_b_fu_122 <= ap_const_lv64_0;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    sum_b_fu_122 <= sum_b_2_fu_597_p3;
                end if;
            end if; 
        end if;
    end process;

    sum_g_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    sum_g_fu_126 <= ap_const_lv64_0;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    sum_g_fu_126 <= sum_g_2_fu_604_p3;
                end if;
            end if; 
        end if;
    end process;

    sum_r_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    sum_r_fu_130 <= ap_const_lv64_0;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    sum_r_fu_130 <= sum_r_2_fu_611_p3;
                end if;
            end if; 
        end if;
    end process;

    x_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    x_fu_142 <= ap_const_lv31_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    x_fu_142 <= add_ln149_fu_313_p2;
                end if;
            end if; 
        end if;
    end process;

    y_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    y_fu_146 <= ap_const_lv31_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    y_fu_146 <= select_ln147_fu_342_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln82_reg_775 <= and_ln82_fu_443_p2;
                and_ln82_reg_775_pp0_iter4_reg <= and_ln82_reg_775;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                icmp_ln147_reg_741_pp0_iter2_reg <= icmp_ln147_reg_741;
                icmp_ln147_reg_741_pp0_iter3_reg <= icmp_ln147_reg_741_pp0_iter2_reg;
                icmp_ln149_reg_745 <= icmp_ln149_fu_296_p2;
                or_ln81_reg_769 <= or_ln81_fu_438_p2;
                or_ln81_reg_769_pp0_iter4_reg <= or_ln81_reg_769;
                tmp_69_reg_791 <= mul_ln98_fu_536_p2(20 downto 20);
                trunc_ln70_s_reg_786 <= mul_ln98_fu_536_p2(19 downto 8);
                trunc_ln81_1_reg_757 <= trunc_ln81_1_fu_309_p1;
                v_36_reg_764 <= v_36_fu_430_p3;
                v_reg_750 <= m_axi_gmem0_RDATA;
                xor_ln82_reg_781 <= xor_ln82_fu_474_p2;
                xor_ln82_reg_781_pp0_iter4_reg <= xor_ln82_reg_781;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln147_reg_741 <= icmp_ln147_fu_271_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln147_1_fu_336_p2 <= std_logic_vector(unsigned(y_fu_146) + unsigned(ap_const_lv31_1));
    add_ln147_fu_276_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_150) + unsigned(ap_const_lv62_1));
    add_ln149_fu_313_p2 <= std_logic_vector(unsigned(select_ln145_fu_301_p3) + unsigned(ap_const_lv31_1));
    add_ln96_18_fu_380_p2 <= std_logic_vector(unsigned(zext_ln96_fu_365_p1) + unsigned(zext_ln96_18_fu_376_p1));
    add_ln96_fu_386_p2 <= std_logic_vector(unsigned(add_ln96_18_fu_380_p2) + unsigned(ap_const_lv25_1FFDFC0));
    and_ln82_fu_443_p2 <= (trunc_ln81_fu_349_p1 and trunc_ln81_1_reg_757);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(m_axi_gmem0_RVALID)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (m_axi_gmem0_RVALID = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln147_fu_271_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln147_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter4_reg, ap_done_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    cnt_b_1_fu_460_p2 <= std_logic_vector(unsigned(cnt_b_fu_138) + unsigned(ap_const_lv64_1));
    cnt_b_2_fu_487_p3 <= 
        cnt_b_1_fu_460_p2 when (and_ln82_fu_443_p2(0) = '1') else 
        cnt_b_fu_138;
    cnt_b_out <= cnt_b_fu_138;

    cnt_b_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln147_reg_741_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln147_reg_741_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            cnt_b_out_ap_vld <= ap_const_logic_1;
        else 
            cnt_b_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cnt_g_1_fu_454_p2 <= std_logic_vector(unsigned(cnt_g_fu_134) + unsigned(ap_const_lv64_1));
    cnt_g_2_fu_479_p3 <= 
        cnt_g_1_fu_454_p2 when (xor_ln82_fu_474_p2(0) = '1') else 
        cnt_g_fu_134;
    cnt_g_out <= cnt_g_fu_134;

    cnt_g_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln147_reg_741_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln147_reg_741_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            cnt_g_out_ap_vld <= ap_const_logic_1;
        else 
            cnt_g_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cnt_r_1_fu_448_p2 <= std_logic_vector(unsigned(cnt_r_fu_118) + unsigned(ap_const_lv64_1));
    cnt_r_2_fu_466_p3 <= 
        cnt_r_fu_118 when (or_ln81_fu_438_p2(0) = '1') else 
        cnt_r_1_fu_448_p2;
    cnt_r_out <= cnt_r_fu_118;

    cnt_r_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln147_reg_741_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln147_reg_741_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            cnt_r_out_ap_vld <= ap_const_logic_1;
        else 
            cnt_r_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    gmem0_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem0_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem0_blk_n_R <= m_axi_gmem0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln147_fu_271_p2 <= "1" when (indvar_flatten_fu_150 = mul_ln147) else "0";
    icmp_ln149_fu_296_p2 <= "1" when (x_fu_142 = width) else "0";
    icmp_ln70_fu_424_p2 <= "0" when (tmp_68_fu_414_p4 = ap_const_lv5_0) else "1";
    icmp_ln95_fu_353_p2 <= "1" when (unsigned(v_reg_750) > unsigned(ap_const_lv16_20)) else "0";
    m_axi_gmem0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv16_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv2_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    mul_ln98_fu_536_p0 <= mul_ln98_fu_536_p00(12 - 1 downto 0);
    mul_ln98_fu_536_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(v_36_reg_764),21));
    mul_ln98_fu_536_p1 <= mul_ln98_fu_536_p10(9 - 1 downto 0);
    mul_ln98_fu_536_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln81_fu_525_p3),21));
    or_ln81_fu_438_p2 <= (trunc_ln81_fu_349_p1 or trunc_ln81_1_reg_757);
    select_ln145_fu_301_p3 <= 
        ap_const_lv31_0 when (icmp_ln149_fu_296_p2(0) = '1') else 
        x_fu_142;
    select_ln147_fu_342_p3 <= 
        add_ln147_1_fu_336_p2 when (icmp_ln149_reg_745(0) = '1') else 
        y_fu_146;
    select_ln70_fu_402_p3 <= 
        tmp_fu_392_p4 when (icmp_ln95_fu_353_p2(0) = '1') else 
        ap_const_lv17_0;
    select_ln81_fu_525_p3 <= 
        select_ln82_fu_518_p3 when (or_ln81_reg_769(0) = '1') else 
        ap_const_lv9_11E;
    select_ln82_fu_518_p3 <= 
        ap_const_lv9_133 when (and_ln82_reg_775(0) = '1') else 
        ap_const_lv9_100;
    sum_b_1_fu_591_p2 <= std_logic_vector(unsigned(sum_b_fu_122) + unsigned(zext_ln155_fu_575_p1));
    sum_b_2_fu_597_p3 <= 
        sum_b_1_fu_591_p2 when (and_ln82_reg_775_pp0_iter4_reg(0) = '1') else 
        sum_b_fu_122;
    sum_b_out <= sum_b_fu_122;

    sum_b_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln147_reg_741_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln147_reg_741_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            sum_b_out_ap_vld <= ap_const_logic_1;
        else 
            sum_b_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sum_g_1_fu_585_p2 <= std_logic_vector(unsigned(sum_g_fu_126) + unsigned(zext_ln155_fu_575_p1));
    sum_g_2_fu_604_p3 <= 
        sum_g_1_fu_585_p2 when (xor_ln82_reg_781_pp0_iter4_reg(0) = '1') else 
        sum_g_fu_126;
    sum_g_out <= sum_g_fu_126;

    sum_g_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln147_reg_741_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln147_reg_741_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            sum_g_out_ap_vld <= ap_const_logic_1;
        else 
            sum_g_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sum_r_1_fu_579_p2 <= std_logic_vector(unsigned(sum_r_fu_130) + unsigned(zext_ln155_fu_575_p1));
    sum_r_2_fu_611_p3 <= 
        sum_r_fu_130 when (or_ln81_reg_769_pp0_iter4_reg(0) = '1') else 
        sum_r_1_fu_579_p2;
    sum_r_out <= sum_r_fu_130;

    sum_r_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln147_reg_741_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln147_reg_741_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            sum_r_out_ap_vld <= ap_const_logic_1;
        else 
            sum_r_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_66_fu_358_p3 <= (v_reg_750 & ap_const_lv8_0);
    tmp_67_fu_369_p3 <= (v_reg_750 & ap_const_lv1_0);
    tmp_68_fu_414_p4 <= select_ln70_fu_402_p3(16 downto 12);
    tmp_fu_392_p4 <= add_ln96_fu_386_p2(24 downto 8);
    trunc_ln70_fu_410_p1 <= select_ln70_fu_402_p3(12 - 1 downto 0);
    trunc_ln81_1_fu_309_p1 <= select_ln145_fu_301_p3(1 - 1 downto 0);
    trunc_ln81_fu_349_p1 <= select_ln147_fu_342_p3(1 - 1 downto 0);
    v_36_fu_430_p3 <= 
        ap_const_lv12_FFF when (icmp_ln70_fu_424_p2(0) = '1') else 
        trunc_ln70_fu_410_p1;
    v_37_fu_569_p3 <= 
        ap_const_lv12_FFF when (tmp_69_reg_791(0) = '1') else 
        trunc_ln70_s_reg_786;
    xor_ln82_fu_474_p2 <= (trunc_ln81_fu_349_p1 xor trunc_ln81_1_reg_757);
    zext_ln155_fu_575_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(v_37_fu_569_p3),64));
    zext_ln96_18_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_67_fu_369_p3),25));
    zext_ln96_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_66_fu_358_p3),25));
end behav;
