-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity NormalISP_p_anonymous_namespace_run_normal_isp is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    raw_bayer : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    rgb_out : IN STD_LOGIC_VECTOR (63 downto 0);
    width : IN STD_LOGIC_VECTOR (30 downto 0);
    height : IN STD_LOGIC_VECTOR (30 downto 0) );
end;


architecture behav of NormalISP_p_anonymous_namespace_run_normal_isp is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv31_7FFFFFFF : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111111111111111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal gmem1_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal gmem1_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal awb_r_reg_215 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal awb_b_reg_220 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_121_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal mul_ln202_reg_225 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln_fu_147_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln_reg_231 : STD_LOGIC_VECTOR (61 downto 0);
    signal sub_i_i_fu_168_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal sub_i_i_reg_241 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal sub11_i_i_fu_175_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal sub11_i_i_reg_247 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start : STD_LOGIC;
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_done : STD_LOGIC;
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_idle : STD_LOGIC;
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_ready : STD_LOGIC;
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWVALID : STD_LOGIC;
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WVALID : STD_LOGIC;
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WSTRB : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WLAST : STD_LOGIC;
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARVALID : STD_LOGIC;
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_RREADY : STD_LOGIC;
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_BREADY : STD_LOGIC;
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_done : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_idle : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_ready : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWVALID : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WVALID : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WSTRB : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WLAST : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARVALID : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_RREADY : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_BREADY : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWVALID : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WVALID : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WLAST : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARVALID : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_RREADY : STD_LOGIC;
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_BREADY : STD_LOGIC;
    signal grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start_reg : STD_LOGIC := '0';
    signal grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal sext_ln202_fu_157_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln202_3_fu_143_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_121_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_121_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_121_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal grp_fu_121_p00 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_fu_121_p10 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component NormalISP_p_anonymous_namespace_awb_gains_q8 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        m_axi_gmem0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
        m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        raw : IN STD_LOGIC_VECTOR (63 downto 0);
        width : IN STD_LOGIC_VECTOR (30 downto 0);
        height : IN STD_LOGIC_VECTOR (30 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component NormalISP_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        m_axi_gmem0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
        m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        mul_ln202 : IN STD_LOGIC_VECTOR (61 downto 0);
        m_axi_gmem1_AWVALID : OUT STD_LOGIC;
        m_axi_gmem1_AWREADY : IN STD_LOGIC;
        m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WVALID : OUT STD_LOGIC;
        m_axi_gmem1_WREADY : IN STD_LOGIC;
        m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_WLAST : OUT STD_LOGIC;
        m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARVALID : OUT STD_LOGIC;
        m_axi_gmem1_ARREADY : IN STD_LOGIC;
        m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RVALID : IN STD_LOGIC;
        m_axi_gmem1_RREADY : OUT STD_LOGIC;
        m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_RLAST : IN STD_LOGIC;
        m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BVALID : IN STD_LOGIC;
        m_axi_gmem1_BREADY : OUT STD_LOGIC;
        m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        sext_ln202 : IN STD_LOGIC_VECTOR (61 downto 0);
        width : IN STD_LOGIC_VECTOR (30 downto 0);
        height : IN STD_LOGIC_VECTOR (30 downto 0);
        zext_ln202 : IN STD_LOGIC_VECTOR (30 downto 0);
        width_cast30 : IN STD_LOGIC_VECTOR (30 downto 0);
        zext_ln202_3 : IN STD_LOGIC_VECTOR (30 downto 0);
        sub11_i_i : IN STD_LOGIC_VECTOR (30 downto 0);
        sub_i_i_cast : IN STD_LOGIC_VECTOR (30 downto 0);
        raw_bayer : IN STD_LOGIC_VECTOR (63 downto 0);
        zext_ln202_1 : IN STD_LOGIC_VECTOR (30 downto 0);
        sub_i_i : IN STD_LOGIC_VECTOR (30 downto 0);
        awb_r : IN STD_LOGIC_VECTOR (31 downto 0);
        awb_b : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component NormalISP_mul_31ns_31ns_62_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (30 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;



begin
    grp_p_anonymous_namespace_awb_gains_q8_fu_85 : component NormalISP_p_anonymous_namespace_awb_gains_q8
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start,
        ap_done => grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_done,
        ap_idle => grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_idle,
        ap_ready => grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_ready,
        m_axi_gmem0_AWVALID => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY => ap_const_logic_0,
        m_axi_gmem0_AWADDR => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY => ap_const_logic_0,
        m_axi_gmem0_WDATA => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WLAST,
        m_axi_gmem0_WID => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WID,
        m_axi_gmem0_WUSER => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY => m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID => m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA => m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST => m_axi_gmem0_RLAST,
        m_axi_gmem0_RID => m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM => m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER => m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP => m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID => ap_const_logic_0,
        m_axi_gmem0_BREADY => grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP => ap_const_lv2_0,
        m_axi_gmem0_BID => ap_const_lv1_0,
        m_axi_gmem0_BUSER => ap_const_lv1_0,
        raw => raw_bayer,
        width => width,
        height => height,
        ap_return_0 => grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_return_0,
        ap_return_1 => grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_return_1);

    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97 : component NormalISP_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start,
        ap_done => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_done,
        ap_idle => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_idle,
        ap_ready => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_ready,
        m_axi_gmem0_AWVALID => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY => ap_const_logic_0,
        m_axi_gmem0_AWADDR => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY => ap_const_logic_0,
        m_axi_gmem0_WDATA => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WLAST,
        m_axi_gmem0_WID => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WID,
        m_axi_gmem0_WUSER => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY => m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID => m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA => m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST => m_axi_gmem0_RLAST,
        m_axi_gmem0_RID => m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM => m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER => m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP => m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID => ap_const_logic_0,
        m_axi_gmem0_BREADY => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP => ap_const_lv2_0,
        m_axi_gmem0_BID => ap_const_lv1_0,
        m_axi_gmem0_BUSER => ap_const_lv1_0,
        mul_ln202 => mul_ln202_reg_225,
        m_axi_gmem1_AWVALID => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY => m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY => m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WLAST,
        m_axi_gmem1_WID => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WID,
        m_axi_gmem1_WUSER => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY => ap_const_logic_0,
        m_axi_gmem1_ARADDR => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID => ap_const_logic_0,
        m_axi_gmem1_RREADY => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA => ap_const_lv32_0,
        m_axi_gmem1_RLAST => ap_const_logic_0,
        m_axi_gmem1_RID => ap_const_lv1_0,
        m_axi_gmem1_RFIFONUM => ap_const_lv9_0,
        m_axi_gmem1_RUSER => ap_const_lv1_0,
        m_axi_gmem1_RRESP => ap_const_lv2_0,
        m_axi_gmem1_BVALID => m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY => grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP => m_axi_gmem1_BRESP,
        m_axi_gmem1_BID => m_axi_gmem1_BID,
        m_axi_gmem1_BUSER => m_axi_gmem1_BUSER,
        sext_ln202 => trunc_ln_reg_231,
        width => width,
        height => height,
        zext_ln202 => sub11_i_i_reg_247,
        width_cast30 => width,
        zext_ln202_3 => height,
        sub11_i_i => sub11_i_i_reg_247,
        sub_i_i_cast => sub_i_i_reg_241,
        raw_bayer => raw_bayer,
        zext_ln202_1 => width,
        sub_i_i => sub_i_i_reg_241,
        awb_r => awb_r_reg_215,
        awb_b => awb_b_reg_220);

    mul_31ns_31ns_62_2_1_U67 : component NormalISP_mul_31ns_31ns_62_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        dout_WIDTH => 62)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_121_p0,
        din1 => grp_fu_121_p1,
        ce => grp_fu_121_ce,
        dout => grp_fu_121_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_ready = ap_const_logic_1)) then 
                    grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_ready = ap_const_logic_1)) then 
                    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                awb_b_reg_220 <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_return_1;
                awb_r_reg_215 <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_return_0;
                mul_ln202_reg_225 <= grp_fu_121_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                sub11_i_i_reg_247 <= sub11_i_i_fu_175_p2;
                sub_i_i_reg_241 <= sub_i_i_fu_168_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                trunc_ln_reg_231 <= rgb_out(63 downto 2);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, m_axi_gmem1_AWREADY, m_axi_gmem1_BVALID, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state2, grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_done, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_done, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((m_axi_gmem1_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (m_axi_gmem1_BVALID = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state10_blk_assign_proc : process(m_axi_gmem1_BVALID)
    begin
        if ((m_axi_gmem1_BVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_done)
    begin
        if ((grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(m_axi_gmem1_AWREADY)
    begin
        if ((m_axi_gmem1_AWREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_done)
    begin
        if ((grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_gmem1_BVALID, ap_CS_fsm_state10)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state10) and (m_axi_gmem1_BVALID = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(m_axi_gmem1_BVALID, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (m_axi_gmem1_BVALID = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    gmem1_blk_n_AW_assign_proc : process(m_axi_gmem1_AWREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            gmem1_blk_n_AW <= m_axi_gmem1_AWREADY;
        else 
            gmem1_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem1_blk_n_B_assign_proc : process(m_axi_gmem1_BVALID, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            gmem1_blk_n_B <= m_axi_gmem1_BVALID;
        else 
            gmem1_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_121_ce_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_done)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_done = ap_const_logic_1)))) then 
            grp_fu_121_ce <= ap_const_logic_1;
        else 
            grp_fu_121_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_121_p0 <= grp_fu_121_p00(31 - 1 downto 0);
    grp_fu_121_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height),62));
    grp_fu_121_p1 <= grp_fu_121_p10(31 - 1 downto 0);
    grp_fu_121_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),62));
    grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start_reg;
    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start_reg;

    m_axi_gmem0_ARADDR_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARADDR, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARADDR, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARADDR <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARADDR;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARADDR <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARADDR;
        else 
            m_axi_gmem0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem0_ARBURST_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARBURST, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARBURST, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARBURST <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARBURST;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARBURST <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARBURST;
        else 
            m_axi_gmem0_ARBURST <= "XX";
        end if; 
    end process;


    m_axi_gmem0_ARCACHE_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARCACHE, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARCACHE, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARCACHE <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARCACHE;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARCACHE <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARCACHE;
        else 
            m_axi_gmem0_ARCACHE <= "XXXX";
        end if; 
    end process;


    m_axi_gmem0_ARID_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARID, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARID, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARID <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARID <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARID;
        else 
            m_axi_gmem0_ARID <= "X";
        end if; 
    end process;


    m_axi_gmem0_ARLEN_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLEN, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLEN, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARLEN <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLEN;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARLEN <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLEN;
        else 
            m_axi_gmem0_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem0_ARLOCK_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLOCK, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLOCK, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARLOCK <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLOCK;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARLOCK <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLOCK;
        else 
            m_axi_gmem0_ARLOCK <= "XX";
        end if; 
    end process;


    m_axi_gmem0_ARPROT_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARPROT, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARPROT, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARPROT <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARPROT;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARPROT <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARPROT;
        else 
            m_axi_gmem0_ARPROT <= "XXX";
        end if; 
    end process;


    m_axi_gmem0_ARQOS_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARQOS, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARQOS, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARQOS <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARQOS;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARQOS <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARQOS;
        else 
            m_axi_gmem0_ARQOS <= "XXXX";
        end if; 
    end process;


    m_axi_gmem0_ARREGION_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARREGION, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARREGION, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARREGION <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARREGION;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARREGION <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARREGION;
        else 
            m_axi_gmem0_ARREGION <= "XXXX";
        end if; 
    end process;


    m_axi_gmem0_ARSIZE_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARSIZE, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARSIZE, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARSIZE <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARSIZE;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARSIZE <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARSIZE;
        else 
            m_axi_gmem0_ARSIZE <= "XXX";
        end if; 
    end process;


    m_axi_gmem0_ARUSER_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARUSER, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARUSER, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARUSER <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARUSER;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARUSER <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARUSER;
        else 
            m_axi_gmem0_ARUSER <= "X";
        end if; 
    end process;


    m_axi_gmem0_ARVALID_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARVALID, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARVALID, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_ARVALID <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARVALID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARVALID <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARVALID;
        else 
            m_axi_gmem0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_RREADY, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_RREADY, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem0_RREADY <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_RREADY;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_RREADY <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_RREADY;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv16_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv2_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    m_axi_gmem1_ARADDR <= ap_const_lv64_0;
    m_axi_gmem1_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_ARID <= ap_const_lv1_0;
    m_axi_gmem1_ARLEN <= ap_const_lv32_0;
    m_axi_gmem1_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_ARUSER <= ap_const_lv1_0;
    m_axi_gmem1_ARVALID <= ap_const_logic_0;

    m_axi_gmem1_AWADDR_assign_proc : process(m_axi_gmem1_AWREADY, ap_CS_fsm_state3, ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWADDR, ap_CS_fsm_state5, sext_ln202_fu_157_p1)
    begin
        if (((m_axi_gmem1_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem1_AWADDR <= sext_ln202_fu_157_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_AWADDR <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWADDR;
        else 
            m_axi_gmem1_AWADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem1_AWBURST_assign_proc : process(ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWBURST, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_AWBURST <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWBURST;
        else 
            m_axi_gmem1_AWBURST <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem1_AWCACHE_assign_proc : process(ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWCACHE, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_AWCACHE <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWCACHE;
        else 
            m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem1_AWID_assign_proc : process(ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWID, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_AWID <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWID;
        else 
            m_axi_gmem1_AWID <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem1_AWLEN_assign_proc : process(m_axi_gmem1_AWREADY, ap_CS_fsm_state3, ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLEN, ap_CS_fsm_state5, zext_ln202_3_fu_143_p1)
    begin
        if (((m_axi_gmem1_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem1_AWLEN <= zext_ln202_3_fu_143_p1(32 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_AWLEN <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLEN;
        else 
            m_axi_gmem1_AWLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem1_AWLOCK_assign_proc : process(ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLOCK, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_AWLOCK <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLOCK;
        else 
            m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem1_AWPROT_assign_proc : process(ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWPROT, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_AWPROT <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWPROT;
        else 
            m_axi_gmem1_AWPROT <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem1_AWQOS_assign_proc : process(ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWQOS, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_AWQOS <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWQOS;
        else 
            m_axi_gmem1_AWQOS <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem1_AWREGION_assign_proc : process(ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWREGION, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_AWREGION <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWREGION;
        else 
            m_axi_gmem1_AWREGION <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem1_AWSIZE_assign_proc : process(ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWSIZE, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_AWSIZE <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWSIZE;
        else 
            m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem1_AWUSER_assign_proc : process(ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWUSER, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_AWUSER <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWUSER;
        else 
            m_axi_gmem1_AWUSER <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem1_AWVALID_assign_proc : process(m_axi_gmem1_AWREADY, ap_CS_fsm_state3, ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWVALID, ap_CS_fsm_state5)
    begin
        if (((m_axi_gmem1_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem1_AWVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_AWVALID <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWVALID;
        else 
            m_axi_gmem1_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem1_BREADY_assign_proc : process(m_axi_gmem1_BVALID, ap_CS_fsm_state10, ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_BREADY, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (m_axi_gmem1_BVALID = ap_const_logic_1))) then 
            m_axi_gmem1_BREADY <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_BREADY <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_BREADY;
        else 
            m_axi_gmem1_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_RREADY <= ap_const_logic_0;
    m_axi_gmem1_WDATA <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WDATA;
    m_axi_gmem1_WID <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WID;
    m_axi_gmem1_WLAST <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WLAST;
    m_axi_gmem1_WSTRB <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WSTRB;
    m_axi_gmem1_WUSER <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WUSER;

    m_axi_gmem1_WVALID_assign_proc : process(ap_CS_fsm_state4, grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WVALID, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_WVALID <= grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WVALID;
        else 
            m_axi_gmem1_WVALID <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln202_fu_157_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_147_p4),64));

    sub11_i_i_fu_175_p2 <= std_logic_vector(unsigned(height) + unsigned(ap_const_lv31_7FFFFFFF));
    sub_i_i_fu_168_p2 <= std_logic_vector(unsigned(width) + unsigned(ap_const_lv31_7FFFFFFF));
    trunc_ln_fu_147_p4 <= rgb_out(63 downto 2);
    zext_ln202_3_fu_143_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln202_reg_225),64));
end behav;
