// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module NormalISP_p_anonymous_namespace_run_normal_isp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        raw_bayer,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        rgb_out,
        width,
        height
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [15:0] m_axi_gmem0_WDATA;
output  [1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [15:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [9:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [63:0] raw_bayer;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [31:0] m_axi_gmem1_WDATA;
output  [3:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [31:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] rgb_out;
input  [30:0] width;
input  [30:0] height;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem0_ARVALID;
reg[63:0] m_axi_gmem0_ARADDR;
reg[0:0] m_axi_gmem0_ARID;
reg[31:0] m_axi_gmem0_ARLEN;
reg[2:0] m_axi_gmem0_ARSIZE;
reg[1:0] m_axi_gmem0_ARBURST;
reg[1:0] m_axi_gmem0_ARLOCK;
reg[3:0] m_axi_gmem0_ARCACHE;
reg[2:0] m_axi_gmem0_ARPROT;
reg[3:0] m_axi_gmem0_ARQOS;
reg[3:0] m_axi_gmem0_ARREGION;
reg[0:0] m_axi_gmem0_ARUSER;
reg m_axi_gmem0_RREADY;
reg m_axi_gmem1_AWVALID;
reg[63:0] m_axi_gmem1_AWADDR;
reg[0:0] m_axi_gmem1_AWID;
reg[31:0] m_axi_gmem1_AWLEN;
reg[2:0] m_axi_gmem1_AWSIZE;
reg[1:0] m_axi_gmem1_AWBURST;
reg[1:0] m_axi_gmem1_AWLOCK;
reg[3:0] m_axi_gmem1_AWCACHE;
reg[2:0] m_axi_gmem1_AWPROT;
reg[3:0] m_axi_gmem1_AWQOS;
reg[3:0] m_axi_gmem1_AWREGION;
reg[0:0] m_axi_gmem1_AWUSER;
reg m_axi_gmem1_WVALID;
reg m_axi_gmem1_BREADY;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem1_blk_n_AW;
wire    ap_CS_fsm_state3;
reg    gmem1_blk_n_B;
wire    ap_CS_fsm_state10;
reg   [31:0] awb_r_reg_215;
wire    ap_CS_fsm_state2;
reg   [31:0] awb_b_reg_220;
wire   [61:0] grp_fu_121_p2;
reg   [61:0] mul_ln202_reg_225;
wire  signed [61:0] trunc_ln_fu_147_p4;
reg   [61:0] trunc_ln_reg_231;
wire   [30:0] sub_i_i_fu_168_p2;
reg   [30:0] sub_i_i_reg_241;
wire    ap_CS_fsm_state4;
wire   [30:0] sub11_i_i_fu_175_p2;
reg   [30:0] sub11_i_i_reg_247;
wire    grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start;
wire    grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_done;
wire    grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_idle;
wire    grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_ready;
wire    grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWVALID;
wire   [63:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWADDR;
wire   [0:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWID;
wire   [31:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWLEN;
wire   [2:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWBURST;
wire   [1:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWPROT;
wire   [3:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWQOS;
wire   [3:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWREGION;
wire   [0:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWUSER;
wire    grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WVALID;
wire   [15:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WDATA;
wire   [1:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WSTRB;
wire    grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WLAST;
wire   [0:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WID;
wire   [0:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WUSER;
wire    grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARVALID;
wire   [63:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARADDR;
wire   [0:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARID;
wire   [31:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLEN;
wire   [2:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARBURST;
wire   [1:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARPROT;
wire   [3:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARQOS;
wire   [3:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARREGION;
wire   [0:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARUSER;
wire    grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_RREADY;
wire    grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_BREADY;
wire   [31:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_return_0;
wire   [31:0] grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_return_1;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_done;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_idle;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_ready;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWVALID;
wire   [63:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWADDR;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWID;
wire   [31:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWLEN;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWBURST;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWPROT;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWQOS;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWREGION;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWUSER;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WVALID;
wire   [15:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WDATA;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WSTRB;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WLAST;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WID;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WUSER;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARVALID;
wire   [63:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARADDR;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARID;
wire   [31:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLEN;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARBURST;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARPROT;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARQOS;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARREGION;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARUSER;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_RREADY;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_BREADY;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWVALID;
wire   [63:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWADDR;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWID;
wire   [31:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLEN;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWBURST;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWPROT;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWQOS;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWREGION;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWUSER;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WVALID;
wire   [31:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WDATA;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WSTRB;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WLAST;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WID;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WUSER;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARVALID;
wire   [63:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARADDR;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARID;
wire   [31:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARLEN;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARBURST;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARPROT;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARQOS;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARREGION;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARUSER;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_RREADY;
wire    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_BREADY;
reg    grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start_reg;
reg    grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start_reg;
wire    ap_CS_fsm_state5;
wire  signed [63:0] sext_ln202_fu_157_p1;
wire   [63:0] zext_ln202_3_fu_143_p1;
wire   [30:0] grp_fu_121_p0;
wire   [30:0] grp_fu_121_p1;
reg    grp_fu_121_ce;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire   [61:0] grp_fu_121_p00;
wire   [61:0] grp_fu_121_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start_reg = 1'b0;
#0 grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start_reg = 1'b0;
end

NormalISP_p_anonymous_namespace_awb_gains_q8 grp_p_anonymous_namespace_awb_gains_q8_fu_85(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start),
    .ap_done(grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_done),
    .ap_idle(grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_ready),
    .m_axi_gmem0_AWVALID(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RFIFONUM(m_axi_gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .raw(raw_bayer),
    .width(width),
    .height(height),
    .ap_return_0(grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_return_0),
    .ap_return_1(grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_return_1)
);

NormalISP_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2 grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start),
    .ap_done(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_done),
    .ap_idle(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_ready),
    .m_axi_gmem0_AWVALID(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RFIFONUM(m_axi_gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .mul_ln202(mul_ln202_reg_225),
    .m_axi_gmem1_AWVALID(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(m_axi_gmem1_AWREADY),
    .m_axi_gmem1_AWADDR(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(m_axi_gmem1_WREADY),
    .m_axi_gmem1_WDATA(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(1'b0),
    .m_axi_gmem1_ARADDR(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(1'b0),
    .m_axi_gmem1_RREADY(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(32'd0),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RFIFONUM(9'd0),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(m_axi_gmem1_BVALID),
    .m_axi_gmem1_BREADY(grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(m_axi_gmem1_BRESP),
    .m_axi_gmem1_BID(m_axi_gmem1_BID),
    .m_axi_gmem1_BUSER(m_axi_gmem1_BUSER),
    .sext_ln202(trunc_ln_reg_231),
    .width(width),
    .height(height),
    .zext_ln202(sub11_i_i_reg_247),
    .width_cast30(width),
    .zext_ln202_3(height),
    .sub11_i_i(sub11_i_i_reg_247),
    .sub_i_i_cast(sub_i_i_reg_241),
    .raw_bayer(raw_bayer),
    .zext_ln202_1(width),
    .sub_i_i(sub_i_i_reg_241),
    .awb_r(awb_r_reg_215),
    .awb_b(awb_b_reg_220)
);

NormalISP_mul_31ns_31ns_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_31ns_31ns_62_2_1_U67(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_121_p0),
    .din1(grp_fu_121_p1),
    .ce(grp_fu_121_ce),
    .dout(grp_fu_121_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        awb_b_reg_220 <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_return_1;
        awb_r_reg_215 <= grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_return_0;
        mul_ln202_reg_225 <= grp_fu_121_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sub11_i_i_reg_247 <= sub11_i_i_fu_175_p2;
        sub_i_i_reg_241 <= sub_i_i_fu_168_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        trunc_ln_reg_231 <= {{rgb_out[63:2]}};
    end
end

always @ (*) begin
    if ((m_axi_gmem1_BVALID == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem1_AWREADY == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state10) & (m_axi_gmem1_BVALID == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (m_axi_gmem1_BVALID == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gmem1_blk_n_AW = m_axi_gmem1_AWREADY;
    end else begin
        gmem1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        gmem1_blk_n_B = m_axi_gmem1_BVALID;
    end else begin
        gmem1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_done == 1'b1)))) begin
        grp_fu_121_ce = 1'b1;
    end else begin
        grp_fu_121_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem0_ARADDR = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARADDR = grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARADDR;
    end else begin
        m_axi_gmem0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem0_ARBURST = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARBURST;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARBURST = grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARBURST;
    end else begin
        m_axi_gmem0_ARBURST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem0_ARCACHE = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARCACHE;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARCACHE = grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARCACHE;
    end else begin
        m_axi_gmem0_ARCACHE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem0_ARID = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARID;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARID = grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARID;
    end else begin
        m_axi_gmem0_ARID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem0_ARLEN = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARLEN = grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLEN;
    end else begin
        m_axi_gmem0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem0_ARLOCK = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARLOCK;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARLOCK = grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARLOCK;
    end else begin
        m_axi_gmem0_ARLOCK = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem0_ARPROT = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARPROT;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARPROT = grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARPROT;
    end else begin
        m_axi_gmem0_ARPROT = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem0_ARQOS = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARQOS;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARQOS = grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARQOS;
    end else begin
        m_axi_gmem0_ARQOS = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem0_ARREGION = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARREGION;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARREGION = grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARREGION;
    end else begin
        m_axi_gmem0_ARREGION = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem0_ARSIZE = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARSIZE;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARSIZE = grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARSIZE;
    end else begin
        m_axi_gmem0_ARSIZE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem0_ARUSER = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARUSER;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARUSER = grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARUSER;
    end else begin
        m_axi_gmem0_ARUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem0_ARVALID = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARVALID = grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_ARVALID;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem0_RREADY = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem0_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_RREADY = grp_p_anonymous_namespace_awb_gains_q8_fu_85_m_axi_gmem0_RREADY;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem1_AWADDR = sext_ln202_fu_157_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_AWADDR = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWADDR;
    end else begin
        m_axi_gmem1_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_AWBURST = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWBURST;
    end else begin
        m_axi_gmem1_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_AWCACHE = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWCACHE;
    end else begin
        m_axi_gmem1_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_AWID = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWID;
    end else begin
        m_axi_gmem1_AWID = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem1_AWLEN = zext_ln202_3_fu_143_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_AWLEN = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLEN;
    end else begin
        m_axi_gmem1_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_AWLOCK = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWLOCK;
    end else begin
        m_axi_gmem1_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_AWPROT = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWPROT;
    end else begin
        m_axi_gmem1_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_AWQOS = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWQOS;
    end else begin
        m_axi_gmem1_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_AWREGION = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWREGION;
    end else begin
        m_axi_gmem1_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_AWSIZE = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWSIZE;
    end else begin
        m_axi_gmem1_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_AWUSER = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWUSER;
    end else begin
        m_axi_gmem1_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem1_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_AWVALID = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_AWVALID;
    end else begin
        m_axi_gmem1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (m_axi_gmem1_BVALID == 1'b1))) begin
        m_axi_gmem1_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_BREADY = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_BREADY;
    end else begin
        m_axi_gmem1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem1_WVALID = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WVALID;
    end else begin
        m_axi_gmem1_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((m_axi_gmem1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (m_axi_gmem1_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_fu_121_p0 = grp_fu_121_p00;

assign grp_fu_121_p00 = height;

assign grp_fu_121_p1 = grp_fu_121_p10;

assign grp_fu_121_p10 = width;

assign grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start = grp_p_anonymous_namespace_awb_gains_q8_fu_85_ap_start_reg;

assign grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_ap_start_reg;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 16'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 2'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign m_axi_gmem1_ARADDR = 64'd0;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd0;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_ARVALID = 1'b0;

assign m_axi_gmem1_RREADY = 1'b0;

assign m_axi_gmem1_WDATA = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WDATA;

assign m_axi_gmem1_WID = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WID;

assign m_axi_gmem1_WLAST = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WLAST;

assign m_axi_gmem1_WSTRB = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WSTRB;

assign m_axi_gmem1_WUSER = grp_p_anonymous_namespace_run_normal_isp_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_204_2_fu_97_m_axi_gmem1_WUSER;

assign sext_ln202_fu_157_p1 = trunc_ln_fu_147_p4;

assign sub11_i_i_fu_175_p2 = ($signed(height) + $signed(31'd2147483647));

assign sub_i_i_fu_168_p2 = ($signed(width) + $signed(31'd2147483647));

assign trunc_ln_fu_147_p4 = {{rgb_out[63:2]}};

assign zext_ln202_3_fu_143_p1 = mul_ln202_reg_225;

endmodule //NormalISP_p_anonymous_namespace_run_normal_isp
