// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="NormalISP_NormalISP,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.920000,HLS_SYN_LAT=2607116,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=9518,HLS_SYN_LUT=12812,HLS_VERSION=2024_1}" *)

module NormalISP (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] raw_bayer;
wire   [63:0] rgb_out;
wire   [31:0] width;
wire   [31:0] height;
reg    out_width_ap_vld;
reg    out_height_ap_vld;
reg   [31:0] height_read_reg_178;
reg   [31:0] width_read_reg_183;
reg   [63:0] rgb_out_read_reg_188;
reg   [63:0] raw_bayer_read_reg_193;
wire   [30:0] trunc_ln250_fu_152_p1;
reg   [30:0] trunc_ln250_reg_198;
wire   [30:0] trunc_ln250_1_fu_156_p1;
reg   [30:0] trunc_ln250_1_reg_203;
wire   [0:0] or_ln262_fu_172_p2;
reg   [0:0] or_ln262_reg_208;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_start;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_done;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_idle;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_ready;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWVALID;
wire   [63:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWADDR;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWID;
wire   [31:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWLEN;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWBURST;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWPROT;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWQOS;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWREGION;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWUSER;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_WVALID;
wire   [15:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_WDATA;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_WSTRB;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_WLAST;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_WID;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_WUSER;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARVALID;
wire   [63:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARADDR;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARID;
wire   [31:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARLEN;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARBURST;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARPROT;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARQOS;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARREGION;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARUSER;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_RREADY;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_BREADY;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWVALID;
wire   [63:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWADDR;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWID;
wire   [31:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWLEN;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWBURST;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWPROT;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWQOS;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWREGION;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWUSER;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WVALID;
wire   [31:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WDATA;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WSTRB;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WLAST;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WID;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WUSER;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARVALID;
wire   [63:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARADDR;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARID;
wire   [31:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARLEN;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARBURST;
wire   [1:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARPROT;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARQOS;
wire   [3:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARREGION;
wire   [0:0] grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARUSER;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_RREADY;
wire    grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_BREADY;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
reg    gmem0_ARVALID;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
reg    gmem0_RREADY;
wire   [15:0] gmem0_RDATA;
wire   [9:0] gmem0_RFIFONUM;
wire    gmem0_BVALID;
reg    gmem1_AWVALID;
wire    gmem1_AWREADY;
reg    gmem1_WVALID;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [31:0] gmem1_RDATA;
wire   [8:0] gmem1_RFIFONUM;
wire    gmem1_BVALID;
reg    gmem1_BREADY;
reg   [31:0] ap_phi_mux_storemerge1_phi_fu_118_p4;
reg   [31:0] storemerge1_reg_114;
wire    ap_CS_fsm_state3;
reg    ap_block_state3_on_subcall_done;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_130_p4;
reg   [31:0] storemerge_reg_126;
reg    grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln262_fu_160_p2;
wire   [0:0] icmp_ln262_1_fu_166_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_start_reg = 1'b0;
end

NormalISP_p_anonymous_namespace_run_normal_isp grp_p_anonymous_namespace_run_normal_isp_fu_138(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_start),
    .ap_done(grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_done),
    .ap_idle(grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_ready),
    .m_axi_gmem0_AWVALID(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(1'b0),
    .m_axi_gmem0_RID(1'd0),
    .m_axi_gmem0_RFIFONUM(gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(1'd0),
    .m_axi_gmem0_RRESP(2'd0),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .raw_bayer(raw_bayer_read_reg_193),
    .m_axi_gmem1_AWVALID(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(gmem1_AWREADY),
    .m_axi_gmem1_AWADDR(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(gmem1_WREADY),
    .m_axi_gmem1_WDATA(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(1'b0),
    .m_axi_gmem1_ARADDR(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(1'b0),
    .m_axi_gmem1_RREADY(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(32'd0),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RFIFONUM(9'd0),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(gmem1_BVALID),
    .m_axi_gmem1_BREADY(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .rgb_out(rgb_out_read_reg_188),
    .width(trunc_ln250_1_reg_203),
    .height(trunc_ln250_reg_198)
);

NormalISP_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .raw_bayer(raw_bayer),
    .rgb_out(rgb_out),
    .width(width),
    .height(height),
    .out_width(ap_phi_mux_storemerge1_phi_fu_118_p4),
    .out_width_ap_vld(out_width_ap_vld),
    .out_height(ap_phi_mux_storemerge_phi_fu_130_p4),
    .out_height_ap_vld(out_height_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

NormalISP_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 10 ),
    .CH0_USER_DW( 16 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem0_ARVALID),
    .I_CH0_ARREADY(gmem0_ARREADY),
    .I_CH0_ARADDR(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARADDR),
    .I_CH0_ARLEN(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARLEN),
    .I_CH0_RVALID(gmem0_RVALID),
    .I_CH0_RREADY(gmem0_RREADY),
    .I_CH0_RDATA(gmem0_RDATA),
    .I_CH0_RFIFONUM(gmem0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem0_WREADY),
    .I_CH0_WDATA(16'd0),
    .I_CH0_WSTRB(2'd0),
    .I_CH0_BVALID(gmem0_BVALID),
    .I_CH0_BREADY(1'b0)
);

NormalISP_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem1_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem1_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem1_RDATA),
    .I_CH0_RFIFONUM(gmem1_RFIFONUM),
    .I_CH0_AWVALID(gmem1_AWVALID),
    .I_CH0_AWREADY(gmem1_AWREADY),
    .I_CH0_AWADDR(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWADDR),
    .I_CH0_AWLEN(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWLEN),
    .I_CH0_WVALID(gmem1_WVALID),
    .I_CH0_WREADY(gmem1_WREADY),
    .I_CH0_WDATA(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WDATA),
    .I_CH0_WSTRB(grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WSTRB),
    .I_CH0_BVALID(gmem1_BVALID),
    .I_CH0_BREADY(gmem1_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (or_ln262_fu_172_p2 == 1'd1) & (ap_start == 1'b1))) begin
        storemerge1_reg_114 <= 32'd0;
    end else if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3) & (or_ln262_reg_208 == 1'd0))) begin
        storemerge1_reg_114 <= width_read_reg_183;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (or_ln262_fu_172_p2 == 1'd1) & (ap_start == 1'b1))) begin
        storemerge_reg_126 <= 32'd0;
    end else if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3) & (or_ln262_reg_208 == 1'd0))) begin
        storemerge_reg_126 <= height_read_reg_178;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        height_read_reg_178 <= height;
        or_ln262_reg_208 <= or_ln262_fu_172_p2;
        raw_bayer_read_reg_193 <= raw_bayer;
        rgb_out_read_reg_188 <= rgb_out;
        trunc_ln250_1_reg_203 <= trunc_ln250_1_fu_156_p1;
        trunc_ln250_reg_198 <= trunc_ln250_fu_152_p1;
        width_read_reg_183 <= width;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (or_ln262_reg_208 == 1'd0))) begin
        ap_phi_mux_storemerge1_phi_fu_118_p4 = width_read_reg_183;
    end else begin
        ap_phi_mux_storemerge1_phi_fu_118_p4 = storemerge1_reg_114;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (or_ln262_reg_208 == 1'd0))) begin
        ap_phi_mux_storemerge_phi_fu_130_p4 = height_read_reg_178;
    end else begin
        ap_phi_mux_storemerge_phi_fu_130_p4 = storemerge_reg_126;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem0_ARVALID = grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_ARVALID;
    end else begin
        gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem0_RREADY = grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem0_RREADY;
    end else begin
        gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_AWVALID = grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_AWVALID;
    end else begin
        gmem1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_BREADY = grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_BREADY;
    end else begin
        gmem1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_WVALID = grp_p_anonymous_namespace_run_normal_isp_fu_138_m_axi_gmem1_WVALID;
    end else begin
        gmem1_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
        out_height_ap_vld = 1'b1;
    end else begin
        out_height_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
        out_width_ap_vld = 1'b1;
    end else begin
        out_width_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (or_ln262_fu_172_p2 == 1'd1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((1'b1 == ap_CS_fsm_state1) & (or_ln262_fu_172_p2 == 1'd0) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_done == 1'b0) & (or_ln262_reg_208 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_start = grp_p_anonymous_namespace_run_normal_isp_fu_138_ap_start_reg;

assign icmp_ln262_1_fu_166_p2 = (($signed(height) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign icmp_ln262_fu_160_p2 = (($signed(width) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign or_ln262_fu_172_p2 = (icmp_ln262_fu_160_p2 | icmp_ln262_1_fu_166_p2);

assign trunc_ln250_1_fu_156_p1 = width[30:0];

assign trunc_ln250_fu_152_p1 = height[30:0];

endmodule //NormalISP
