// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module NormalISP_p_anonymous_namespace_awb_gains_q8_Pipeline_VITIS_LOOP_147_1_VITIS_LOOP_149_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        mul_ln147,
        sext_ln147,
        width,
        cnt_b_out,
        cnt_b_out_ap_vld,
        cnt_g_out,
        cnt_g_out_ap_vld,
        sum_r_out,
        sum_r_out_ap_vld,
        sum_g_out,
        sum_g_out_ap_vld,
        sum_b_out,
        sum_b_out_ap_vld,
        cnt_r_out,
        cnt_r_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [15:0] m_axi_gmem0_WDATA;
output  [1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [15:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [9:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [61:0] mul_ln147;
input  [62:0] sext_ln147;
input  [30:0] width;
output  [63:0] cnt_b_out;
output   cnt_b_out_ap_vld;
output  [63:0] cnt_g_out;
output   cnt_g_out_ap_vld;
output  [63:0] sum_r_out;
output   sum_r_out_ap_vld;
output  [63:0] sum_g_out;
output   sum_g_out_ap_vld;
output  [63:0] sum_b_out;
output   sum_b_out_ap_vld;
output  [63:0] cnt_r_out;
output   cnt_r_out_ap_vld;

reg ap_idle;
reg m_axi_gmem0_RREADY;
reg cnt_b_out_ap_vld;
reg cnt_g_out_ap_vld;
reg sum_r_out_ap_vld;
reg sum_g_out_ap_vld;
reg sum_b_out_ap_vld;
reg cnt_r_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln147_fu_271_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln147_reg_741;
reg   [0:0] icmp_ln147_reg_741_pp0_iter2_reg;
reg   [0:0] icmp_ln147_reg_741_pp0_iter3_reg;
wire   [0:0] icmp_ln149_fu_296_p2;
reg   [0:0] icmp_ln149_reg_745;
reg   [15:0] v_reg_750;
wire   [0:0] trunc_ln81_1_fu_309_p1;
reg   [0:0] trunc_ln81_1_reg_757;
wire   [11:0] v_36_fu_430_p3;
reg   [11:0] v_36_reg_764;
wire   [0:0] or_ln81_fu_438_p2;
reg   [0:0] or_ln81_reg_769;
reg   [0:0] or_ln81_reg_769_pp0_iter4_reg;
wire   [0:0] and_ln82_fu_443_p2;
reg   [0:0] and_ln82_reg_775;
reg   [0:0] and_ln82_reg_775_pp0_iter4_reg;
wire   [0:0] xor_ln82_fu_474_p2;
reg   [0:0] xor_ln82_reg_781;
reg   [0:0] xor_ln82_reg_781_pp0_iter4_reg;
reg   [11:0] trunc_ln70_s_reg_786;
reg   [0:0] tmp_69_reg_791;
reg   [63:0] cnt_r_fu_118;
wire   [63:0] cnt_r_2_fu_466_p3;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [63:0] sum_b_fu_122;
wire   [63:0] sum_b_2_fu_597_p3;
reg   [63:0] sum_g_fu_126;
wire   [63:0] sum_g_2_fu_604_p3;
reg   [63:0] sum_r_fu_130;
wire   [63:0] sum_r_2_fu_611_p3;
reg   [63:0] cnt_g_fu_134;
wire   [63:0] cnt_g_2_fu_479_p3;
reg   [63:0] cnt_b_fu_138;
wire   [63:0] cnt_b_2_fu_487_p3;
reg   [30:0] x_fu_142;
wire   [30:0] add_ln149_fu_313_p2;
reg   [30:0] y_fu_146;
wire   [30:0] select_ln147_fu_342_p3;
reg   [61:0] indvar_flatten_fu_150;
wire   [61:0] add_ln147_fu_276_p2;
reg    ap_block_pp0_stage0_01001;
wire   [30:0] select_ln145_fu_301_p3;
wire   [30:0] add_ln147_1_fu_336_p2;
wire   [23:0] tmp_66_fu_358_p3;
wire   [16:0] tmp_67_fu_369_p3;
wire   [24:0] zext_ln96_fu_365_p1;
wire   [24:0] zext_ln96_18_fu_376_p1;
wire   [24:0] add_ln96_18_fu_380_p2;
wire   [24:0] add_ln96_fu_386_p2;
wire   [0:0] icmp_ln95_fu_353_p2;
wire   [16:0] tmp_fu_392_p4;
wire   [16:0] select_ln70_fu_402_p3;
wire   [4:0] tmp_68_fu_414_p4;
wire   [0:0] icmp_ln70_fu_424_p2;
wire   [11:0] trunc_ln70_fu_410_p1;
wire   [0:0] trunc_ln81_fu_349_p1;
wire   [63:0] cnt_r_1_fu_448_p2;
wire   [63:0] cnt_g_1_fu_454_p2;
wire   [63:0] cnt_b_1_fu_460_p2;
wire   [8:0] select_ln82_fu_518_p3;
wire   [8:0] select_ln81_fu_525_p3;
wire   [11:0] mul_ln98_fu_536_p0;
wire   [8:0] mul_ln98_fu_536_p1;
wire   [20:0] mul_ln98_fu_536_p2;
wire   [11:0] v_37_fu_569_p3;
wire   [63:0] zext_ln155_fu_575_p1;
wire   [63:0] sum_b_1_fu_591_p2;
wire   [63:0] sum_g_1_fu_585_p2;
wire   [63:0] sum_r_1_fu_579_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [20:0] mul_ln98_fu_536_p00;
wire   [20:0] mul_ln98_fu_536_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 cnt_r_fu_118 = 64'd0;
#0 sum_b_fu_122 = 64'd0;
#0 sum_g_fu_126 = 64'd0;
#0 sum_r_fu_130 = 64'd0;
#0 cnt_g_fu_134 = 64'd0;
#0 cnt_b_fu_138 = 64'd0;
#0 x_fu_142 = 31'd0;
#0 y_fu_146 = 31'd0;
#0 indvar_flatten_fu_150 = 62'd0;
#0 ap_done_reg = 1'b0;
end

NormalISP_mul_12ns_9ns_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 21 ))
mul_12ns_9ns_21_1_1_U1(
    .din0(mul_ln98_fu_536_p0),
    .din1(mul_ln98_fu_536_p1),
    .dout(mul_ln98_fu_536_p2)
);

NormalISP_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cnt_b_fu_138 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            cnt_b_fu_138 <= cnt_b_2_fu_487_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cnt_g_fu_134 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            cnt_g_fu_134 <= cnt_g_2_fu_479_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cnt_r_fu_118 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            cnt_r_fu_118 <= cnt_r_2_fu_466_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_150 <= 62'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln147_fu_271_p2 == 1'd0))) begin
            indvar_flatten_fu_150 <= add_ln147_fu_276_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_b_fu_122 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            sum_b_fu_122 <= sum_b_2_fu_597_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_g_fu_126 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            sum_g_fu_126 <= sum_g_2_fu_604_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_r_fu_130 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            sum_r_fu_130 <= sum_r_2_fu_611_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            x_fu_142 <= 31'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            x_fu_142 <= add_ln149_fu_313_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            y_fu_146 <= 31'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            y_fu_146 <= select_ln147_fu_342_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln82_reg_775 <= and_ln82_fu_443_p2;
        and_ln82_reg_775_pp0_iter4_reg <= and_ln82_reg_775;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln147_reg_741_pp0_iter2_reg <= icmp_ln147_reg_741;
        icmp_ln147_reg_741_pp0_iter3_reg <= icmp_ln147_reg_741_pp0_iter2_reg;
        icmp_ln149_reg_745 <= icmp_ln149_fu_296_p2;
        or_ln81_reg_769 <= or_ln81_fu_438_p2;
        or_ln81_reg_769_pp0_iter4_reg <= or_ln81_reg_769;
        tmp_69_reg_791 <= mul_ln98_fu_536_p2[32'd20];
        trunc_ln70_s_reg_786 <= {{mul_ln98_fu_536_p2[19:8]}};
        trunc_ln81_1_reg_757 <= trunc_ln81_1_fu_309_p1;
        v_36_reg_764 <= v_36_fu_430_p3;
        v_reg_750 <= m_axi_gmem0_RDATA;
        xor_ln82_reg_781 <= xor_ln82_fu_474_p2;
        xor_ln82_reg_781_pp0_iter4_reg <= xor_ln82_reg_781;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln147_reg_741 <= icmp_ln147_fu_271_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln147_fu_271_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln147_reg_741_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnt_b_out_ap_vld = 1'b1;
    end else begin
        cnt_b_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln147_reg_741_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnt_g_out_ap_vld = 1'b1;
    end else begin
        cnt_g_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln147_reg_741_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnt_r_out_ap_vld = 1'b1;
    end else begin
        cnt_r_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln147_reg_741_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_b_out_ap_vld = 1'b1;
    end else begin
        sum_b_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln147_reg_741_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_g_out_ap_vld = 1'b1;
    end else begin
        sum_g_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln147_reg_741_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_r_out_ap_vld = 1'b1;
    end else begin
        sum_r_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln147_1_fu_336_p2 = (y_fu_146 + 31'd1);

assign add_ln147_fu_276_p2 = (indvar_flatten_fu_150 + 62'd1);

assign add_ln149_fu_313_p2 = (select_ln145_fu_301_p3 + 31'd1);

assign add_ln96_18_fu_380_p2 = (zext_ln96_fu_365_p1 + zext_ln96_18_fu_376_p1);

assign add_ln96_fu_386_p2 = ($signed(add_ln96_18_fu_380_p2) + $signed(25'd33546176));

assign and_ln82_fu_443_p2 = (trunc_ln81_fu_349_p1 & trunc_ln81_1_reg_757);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (m_axi_gmem0_RVALID == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign cnt_b_1_fu_460_p2 = (cnt_b_fu_138 + 64'd1);

assign cnt_b_2_fu_487_p3 = ((and_ln82_fu_443_p2[0:0] == 1'b1) ? cnt_b_1_fu_460_p2 : cnt_b_fu_138);

assign cnt_b_out = cnt_b_fu_138;

assign cnt_g_1_fu_454_p2 = (cnt_g_fu_134 + 64'd1);

assign cnt_g_2_fu_479_p3 = ((xor_ln82_fu_474_p2[0:0] == 1'b1) ? cnt_g_1_fu_454_p2 : cnt_g_fu_134);

assign cnt_g_out = cnt_g_fu_134;

assign cnt_r_1_fu_448_p2 = (cnt_r_fu_118 + 64'd1);

assign cnt_r_2_fu_466_p3 = ((or_ln81_fu_438_p2[0:0] == 1'b1) ? cnt_r_fu_118 : cnt_r_1_fu_448_p2);

assign cnt_r_out = cnt_r_fu_118;

assign icmp_ln147_fu_271_p2 = ((indvar_flatten_fu_150 == mul_ln147) ? 1'b1 : 1'b0);

assign icmp_ln149_fu_296_p2 = ((x_fu_142 == width) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_424_p2 = ((tmp_68_fu_414_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_353_p2 = ((v_reg_750 > 16'd32) ? 1'b1 : 1'b0);

assign m_axi_gmem0_ARADDR = 64'd0;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 32'd0;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_ARVALID = 1'b0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 16'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 2'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign mul_ln98_fu_536_p0 = mul_ln98_fu_536_p00;

assign mul_ln98_fu_536_p00 = v_36_reg_764;

assign mul_ln98_fu_536_p1 = mul_ln98_fu_536_p10;

assign mul_ln98_fu_536_p10 = select_ln81_fu_525_p3;

assign or_ln81_fu_438_p2 = (trunc_ln81_fu_349_p1 | trunc_ln81_1_reg_757);

assign select_ln145_fu_301_p3 = ((icmp_ln149_fu_296_p2[0:0] == 1'b1) ? 31'd0 : x_fu_142);

assign select_ln147_fu_342_p3 = ((icmp_ln149_reg_745[0:0] == 1'b1) ? add_ln147_1_fu_336_p2 : y_fu_146);

assign select_ln70_fu_402_p3 = ((icmp_ln95_fu_353_p2[0:0] == 1'b1) ? tmp_fu_392_p4 : 17'd0);

assign select_ln81_fu_525_p3 = ((or_ln81_reg_769[0:0] == 1'b1) ? select_ln82_fu_518_p3 : 9'd286);

assign select_ln82_fu_518_p3 = ((and_ln82_reg_775[0:0] == 1'b1) ? 9'd307 : 9'd256);

assign sum_b_1_fu_591_p2 = (sum_b_fu_122 + zext_ln155_fu_575_p1);

assign sum_b_2_fu_597_p3 = ((and_ln82_reg_775_pp0_iter4_reg[0:0] == 1'b1) ? sum_b_1_fu_591_p2 : sum_b_fu_122);

assign sum_b_out = sum_b_fu_122;

assign sum_g_1_fu_585_p2 = (sum_g_fu_126 + zext_ln155_fu_575_p1);

assign sum_g_2_fu_604_p3 = ((xor_ln82_reg_781_pp0_iter4_reg[0:0] == 1'b1) ? sum_g_1_fu_585_p2 : sum_g_fu_126);

assign sum_g_out = sum_g_fu_126;

assign sum_r_1_fu_579_p2 = (sum_r_fu_130 + zext_ln155_fu_575_p1);

assign sum_r_2_fu_611_p3 = ((or_ln81_reg_769_pp0_iter4_reg[0:0] == 1'b1) ? sum_r_fu_130 : sum_r_1_fu_579_p2);

assign sum_r_out = sum_r_fu_130;

assign tmp_66_fu_358_p3 = {{v_reg_750}, {8'd0}};

assign tmp_67_fu_369_p3 = {{v_reg_750}, {1'd0}};

assign tmp_68_fu_414_p4 = {{select_ln70_fu_402_p3[16:12]}};

assign tmp_fu_392_p4 = {{add_ln96_fu_386_p2[24:8]}};

assign trunc_ln70_fu_410_p1 = select_ln70_fu_402_p3[11:0];

assign trunc_ln81_1_fu_309_p1 = select_ln145_fu_301_p3[0:0];

assign trunc_ln81_fu_349_p1 = select_ln147_fu_342_p3[0:0];

assign v_36_fu_430_p3 = ((icmp_ln70_fu_424_p2[0:0] == 1'b1) ? 12'd4095 : trunc_ln70_fu_410_p1);

assign v_37_fu_569_p3 = ((tmp_69_reg_791[0:0] == 1'b1) ? 12'd4095 : trunc_ln70_s_reg_786);

assign xor_ln82_fu_474_p2 = (trunc_ln81_fu_349_p1 ^ trunc_ln81_1_reg_757);

assign zext_ln155_fu_575_p1 = v_37_fu_569_p3;

assign zext_ln96_18_fu_376_p1 = tmp_67_fu_369_p3;

assign zext_ln96_fu_365_p1 = tmp_66_fu_358_p3;

endmodule //NormalISP_p_anonymous_namespace_awb_gains_q8_Pipeline_VITIS_LOOP_147_1_VITIS_LOOP_149_2
