#!/usr/bin/env python3
"""Generate the fabric-only DFX static wrapper from two Vivado synth stubs."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Port:
    direction: str
    width: str
    name: str


DECL_RE = re.compile(
    r"^\s*(input|output|inout)\s+(?:(?:wire|reg)\s+)?"
    r"(\[[^\]]+\]\s*)?([A-Za-z_][A-Za-z0-9_$]*)\s*(?:/\*.*?\*/\s*)?;",
    re.MULTILINE,
)


def parse_stub(path: Path) -> tuple[str, list[Port]]:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_$]*)\b", text, re.MULTILINE)
    if not match:
        raise ValueError(f"no module declaration in {path}")
    ports = [Port(d, (w or "").strip(), n) for d, w, n in DECL_RE.findall(text)]
    if not ports:
        raise ValueError(f"no non-ANSI port declarations in {path}")
    return match.group(1), ports


def signature(ports: list[Port]) -> list[tuple[str, str, str]]:
    return [(p.direction, re.sub(r"\s+", "", p.width), p.name) for p in ports]


def width_decl(port: Port) -> str:
    return f" {port.width}" if port.width else ""


def zero_value(port: Port) -> str:
    return "0"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("normal_stub", type=Path)
    parser.add_argument("lowlight_stub", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    normal_module, normal_ports = parse_stub(args.normal_stub)
    _, lowlight_ports = parse_stub(args.lowlight_stub)
    if signature(normal_ports) != signature(lowlight_ports):
        raise SystemExit("RM stub port signatures differ; refusing to generate DFX wrapper")

    clock_names = {"ap_clk", "ap_rst_n"}
    lines = [
        "// Generated by generate_static_wrapper.py; do not edit manually.",
        "`timescale 1ns/1ps",
        "(* black_box = \"true\" *)",
        f"module {normal_module}(",
        "    " + ",\n    ".join(p.name for p in normal_ports),
        ");",
    ]
    for port in normal_ports:
        lines.append(f"  {port.direction} wire{width_decl(port)} {port.name};")
    lines.extend(["endmodule", "", "module dfx_static_top(input wire ap_clk, input wire ap_rst_n);"])

    observed = []
    for port in normal_ports:
        if port.name in clock_names:
            continue
        if port.direction == "input":
            lines.append(f"  wire{width_decl(port)} tie_{port.name} = {zero_value(port)};")
        elif port.direction == "output":
            lines.append(f"  wire{width_decl(port)} obs_{port.name};")
            observed.append(port.name)
        else:
            lines.append(f"  wire{width_decl(port)} io_{port.name};")

    lines.extend([
        "  (* dont_touch = \"true\", keep_hierarchy = \"yes\" *)",
        f"  {normal_module} u_rp (",
    ])
    connections = []
    for port in normal_ports:
        if port.name in clock_names:
            signal = port.name
        elif port.direction == "input":
            signal = f"tie_{port.name}"
        elif port.direction == "output":
            signal = f"obs_{port.name}"
        else:
            signal = f"io_{port.name}"
        connections.append(f"    .{port.name}({signal})")
    lines.append(",\n".join(connections))
    lines.append("  );")
    if observed:
        expr = " ^ ".join(f"^obs_{name}" for name in observed)
        lines.append(f"  (* keep = \"true\" *) wire observation_xor = {expr};")
    lines.extend(["endmodule", ""])
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {args.output}: {len(normal_ports)} ports; signatures identical")


if __name__ == "__main__":
    main()
