#!/usr/bin/env python3
"""Generate a fabric-only FLAT wrapper for a single HLS top.

Same tie-off technique as scripts/dfx/generate_static_wrapper.py (only
ap_clk/ap_rst_n leave the chip; all other inputs tie to 0 and all outputs
XOR-reduce into one kept observation net, so nothing is optimised away and
the ~662 signal bits do not blow the 360-pin budget). The difference: no
black box and no DFX partition -- the DUT is synthesised in place, which is
what makes this a flat Arm1/Arm2 implementation comparable to Arm3's
config1/config2 post-route numbers.

Port parsing is reused from the DFX generator so both flows agree.
"""
import argparse
import importlib.util
import sys
from pathlib import Path

DFX_GEN = Path("/home/mini/workspace/dfxisp/.claude/worktrees/hw-interface-prompt"
               "/isppipeline/hls/scripts/dfx/generate_static_wrapper.py")


def load_dfx_gen():
    spec = importlib.util.spec_from_file_location("gsw", DFX_GEN)
    mod = importlib.util.module_from_spec(spec)
    # Must be registered before exec: @dataclass resolves cls.__module__ via
    # sys.modules, and Vivado's bundled Python 3.8 raises AttributeError
    # ('NoneType' has no __dict__) if the module is absent.
    sys.modules["gsw"] = mod
    spec.loader.exec_module(mod)
    return mod


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("stub", type=Path)
    ap.add_argument("output", type=Path)
    ap.add_argument("--top", default="flat_top")
    args = ap.parse_args()

    g = load_dfx_gen()
    module, ports = g.parse_stub(args.stub)
    clock_names = {"ap_clk", "ap_rst_n"}

    lines = [
        "// Generated by gen_flat_wrapper.py; do not edit manually.",
        "`timescale 1ns/1ps",
        f"module {args.top}(input wire ap_clk, input wire ap_rst_n);",
    ]
    observed = []
    for p in ports:
        if p.name in clock_names:
            continue
        w = g.width_decl(p)
        if p.direction == "input":
            lines.append(f"  wire{w} tie_{p.name} = 0;")
        elif p.direction == "output":
            lines.append(f"  wire{w} obs_{p.name};")
            observed.append(p.name)
        else:
            lines.append(f"  wire{w} io_{p.name};")

    lines.append('  (* dont_touch = "true", keep_hierarchy = "yes" *)')
    lines.append(f"  {module} u_dut (")
    conns = []
    for p in ports:
        if p.name in clock_names:
            sig = p.name
        elif p.direction == "input":
            sig = f"tie_{p.name}"
        elif p.direction == "output":
            sig = f"obs_{p.name}"
        else:
            sig = f"io_{p.name}"
        conns.append(f"    .{p.name}({sig})")
    lines.append(",\n".join(conns))
    lines.append("  );")
    if observed:
        expr = " ^ ".join(f"^obs_{n}" for n in observed)
        lines.append(f'  (* keep = "true" *) wire observation_xor = {expr};')
    lines.extend(["endmodule", ""])
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {args.output}: module={module}, {len(ports)} ports, "
          f"{len(observed)} observed outputs")


if __name__ == "__main__":
    main()
